name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: MyProject.sln  # 🔹 Replace with your actual solution file name
      Test_Project_Path: MyProject.Tests/MyProject.Tests.csproj  # 🔹 Replace with your test project path
      Wap_Project_Directory: MyProject.Package  # 🔹 Replace with your WAP project directory
      Wap_Project_Path: MyProject.Package/MyProject.Package.wapproj  # 🔹 Replace with your WAP project path

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug - List Files in Repo
      run: ls -R  # 🔹 This helps verify that the solution file exists

    # Install .NET SDK
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Run Unit Tests
    - name: Run Unit Tests
      run: dotnet test ${{ env.Test_Project_Path }}

    # Restore Dependencies
    - name: Restore the Application
      run: dotnet restore ${{ env.Solution_Name }}
      env:
        Configuration: ${{ matrix.configuration }}

    # Decode the Base64-encoded PFX certificate
    - name: Decode the PFX Certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Build and Package the Windows Application Packaging (WAP) Project
    - name: Create the App Package
      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Remove the PFX Certificate After Use
    - name: Remove PFX Certificate
      run: Remove-Item -Path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    # Upload Build Artifacts (MSIX Package)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
